version: '3.8'
services:
  web:
    build: .
    user: root
    ports:
      - "8080:80"
    container_name: servidor-web-compose
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
